### ISSUE TITLE
Using other methods to jump to the route will report an error

### ISSUE THREAD

**Issue by lizhuoyuan** [lslv1243/pip_view#14]
this is ok: 
` Navigator.of(context).push(MaterialPageRoute(builder: (context) => MePage(),));`

`context.pushNamed(me);`
error:
```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
Here is the subtree for one of the offending heroes: Hero
  tag: <default FloatingActionButton tag>
  state: _HeroState#e8d94
When the exception was thrown, this was the stack: 
#0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:283:11)
#1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:294:8)
#2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:313:11)
#3      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#6      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#7      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#8      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#10     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#11     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#12     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#14     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#15     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
#16     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#17     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#18     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#20     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#21     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#22     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#23     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
#24     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#26     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#28     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#30     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#32     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#34     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#36     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#38     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#39     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#40     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#42     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#44     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#46     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#48     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#50     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#51     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#52     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#54     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#56     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#57     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#58     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#59     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#60     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#61     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#62     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#63     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#64     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#66     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#67     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#68     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#69     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#70     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#72     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#74     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#75     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#76     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#77     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#78     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#79     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#80     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#81     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#82     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#84     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#85     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#86     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#87     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#88     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#90     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#91     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#92     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#93     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#94     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#96     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#97     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#98     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#99     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#100    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#102    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#103    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
#104    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#105    _LayoutBuilderElement.visitChildren (package:flutter/src/widgets/layout_builder.dart:67:14)
#106    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#107    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#108    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#109    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#110    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#111    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#112    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#113    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#114    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#115    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#116    Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:328:15)
#117    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#118    Element.visitChildElements (package:flutter/src/widgets/framework.dart:3466:5)
#119    Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:331:13)
#120    HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:945:14)
#121    HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:899:11)
#122    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#123    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:9)
#124    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#125    _invoke (dart:ui/hooks.dart:148:13)
#126    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#127    _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================
```

**Comment by sagnik-sanyal** [comment]
I think named routes already in the application simply doesn't work when the pip view is active . Did you get any solution for the above problem ??

**Comment by lizhuoyuan** [comment]
I used the original route hopping method to solve the problem temporarily

**Comment by Eimji** [comment]
Hello

I think you need to call Navigator.of(context, rootNavigator: true).pushNamed() instead of Navigator.pushName() which defaults to rootNavigator == false, so it uses the Navigator of pip_view.

As pip_view uses its own Navigaor, you need to pay attention when pushing a route to avoid confusion between your navigator and the one created by pip_view. You may also modify the code in pip_view.dart to expose the Navigator key so that you can use _pipViewNavigatorKey.currentState!.pushNamed when you want to push a route within the 'pip view stack'.
